### ISSUE TITLE
Number of issues

### ISSUE THREAD

**Issue by WinstonMDP** [jesseleite/nvim-noirbuddy#6]
Hello, I have number of issues:
1. I tried to change color of text under cursor, but my solution doesn't work (it is pink, not black).
![screen-1679679524](https://user-images.githubusercontent.com/61916541/227600044-19d42d63-4b68-4282-8419-68b427762668.png)
2. Also I don't know how to change color of this orange line and exclude it.
![screen-1679679630](https://user-images.githubusercontent.com/61916541/227600383-31acbeab-b07e-42fc-92b7-0725fbaa1e78.png)
3. How to change color of visual section on lualine?
![screen-1679679691](https://user-images.githubusercontent.com/61916541/227600564-599ba041-b545-453b-a9a5-8f8292c1d3c2.png)

**Comment by WinstonMDP** [comment]
First issue was solved. I have change cursor colors in my alacritty config

**Comment by n1ghtmare** [comment]
I'm not in front of a computer to test things out for you, but for the second "issue" you have (the underline), the underline color is tied to the `diagnostic_warning` color, so to change how it appears, you could try something like (and change it to whatever color you like):

```
require("noirbuddy").setup {
  colors = {
    diagnostic_warning = '#ff7700'
  },
}
```
As for the lualine, check out my lualine config (it's using this theme), copy paste the "second option" and play with the colors:

 https://github.com/n1ghtmare/dotfiles/blob/master/nvim/lua/c/lualine.lua

**Comment by WinstonMDP** [comment]
I have already done this for diagnostic_warning, but it doesn't work(
